Repository aidotse/PASEOS, pull requests merged in 2023-02, with the labels that each got.

#104 Adding rtgs
  README.md
  paseos/__init__.py
  paseos/actors/actor_builder.py
  paseos/actors/spacecraft_actor.py
  paseos/power/charge_model.py
  paseos/power/power_device_type.py
  paseos/tests/power_test.py
Labels: documentation, enhancement, tests, feature, user-facing, physical-model, v0.1.0

#115 Adding release process and actions
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/deploy_to_pypi.yml
  .github/workflows/deploy_to_test_pypi.yml
Labels: enhancement, release, v0.1.0

#116 Small fixes for 0.1.0
  README.md
  examples/Sentinel_2_example_notebook/Sentinel2_example_notebook.ipynb
  paseos/actors/actor_builder.py
  paseos/paseos.py
Labels: documentation, enhancement, example, feature, user-facing, v0.1.0

#120 Further steps for release v0.1.0
  README.md
  environment.yml
  examples/Sentinel_2_example_notebook/Sentinel2_example_notebook.ipynb
  requirements.txt
  setup.py
Labels: documentation, release, v0.1.0

#123 Fixes for release
  .github/workflows/deploy_to_pypi.yml
  .github/workflows/deploy_to_test_pypi.yml
  environment.yml
  requirements.txt
  setup.py
Labels: bug, release, v0.1.0

#121 Mpi example
  README.md
  examples/Constellation_example/constellation.ipynb
  examples/MPI_example/mpi_example.py
  examples/MPI_example/mpi_utility_func.py
  examples/utils/get_constellation.py
  paseos/paseos.py
Labels: documentation, example, user-facing

#126 Small fixes in visualization
  paseos/visualization/space_animation.py
Labels: bug, visualization, user-facing

#135 Fix broken learning example
  examples/Learning_example/learning_example.ipynb
Labels: bug

#143 Provide access to local and simulation time of instance
  README.md
  paseos/paseos.py
Labels: documentation, enhancement, user-facing, physical-model

#132 fixed typo in function name
  examples/Constellation_example/constellation.ipynb
  examples/MPI_example/mpi_utility_func.py
  paseos/paseos.py
Labels: bug

#131 Skipping LOS betweens ground stations
  paseos/visualization/space_animation.py
Labels: bug
